# Source Generated with Decompyle++
# File: csv.pyc (Python 3.14)

'''
CSV parsing and writing.

This module provides classes that assist in the reading and writing
of Comma Separated Value (CSV) files, and implements the interface
described by PEP 305.  Although many CSV files are simple to parse,
the format is not formally defined by a stable specification and
is subtle enough that parsing lines of a CSV file with something
like line.split(",") is bound to fail.  The module supports three
basic APIs: reading, writing, and registration of dialects.


DIALECT REGISTRATION:

Readers and writers support a dialect argument, which is a convenient
handle on a group of settings.  When the dialect argument is a string,
it identifies one of the dialects previously registered with the module.
If it is a class or instance, the attributes of the argument are used as
the settings for the reader or writer:

    class excel:
        delimiter = \',\'
        quotechar = \'"\'
        escapechar = None
        doublequote = True
        skipinitialspace = False
        lineterminator = \'\\r\\n\'
        quoting = QUOTE_MINIMAL

SETTINGS:

    * quotechar - specifies a one-character string to use as the
        quoting character.  It defaults to \'"\'.
    * delimiter - specifies a one-character string to use as the
        field separator.  It defaults to \',\'.
    * skipinitialspace - specifies how to interpret spaces which
        immediately follow a delimiter.  It defaults to False, which
        means that spaces immediately following a delimiter is part
        of the following field.
    * lineterminator - specifies the character sequence which should
        terminate rows.
    * quoting - controls when quotes should be generated by the writer.
        It can take on any of the following module constants:

        csv.QUOTE_MINIMAL means only when required, for example, when a
            field contains either the quotechar or the delimiter
        csv.QUOTE_ALL means that quotes are always placed around fields.
        csv.QUOTE_NONNUMERIC means that quotes are always placed around
            fields which do not parse as integers or floating-point
            numbers.
        csv.QUOTE_STRINGS means that quotes are always placed around
            fields which are strings.  Note that the Python value None
            is not a string.
        csv.QUOTE_NOTNULL means that quotes are only placed around fields
            that are not the Python value None.
        csv.QUOTE_NONE means that quotes are never placed around fields.
    * escapechar - specifies a one-character string used to escape
        the delimiter when quoting is set to QUOTE_NONE.
    * doublequote - controls the handling of quotes inside fields.  When
        True, two consecutive quotes are interpreted as one during read,
        and when writing, each quote character embedded in the data is
        written as two quotes
'''
import types
from _csv import Error, writer, reader, register_dialect, unregister_dialect, get_dialect, list_dialects, field_size_limit, QUOTE_MINIMAL, QUOTE_ALL, QUOTE_NONNUMERIC, QUOTE_NONE, QUOTE_STRINGS, QUOTE_NOTNULL
from _csv import Dialect as _Dialect
from io import StringIO
__all__ = [
    'QUOTE_MINIMAL',
    'QUOTE_ALL',
    'QUOTE_NONNUMERIC',
    'QUOTE_NONE',
    'QUOTE_STRINGS',
    'QUOTE_NOTNULL',
    'Error',
    'Dialect',
    'excel',
    'excel_tab',
    'field_size_limit',
    'reader',
    'writer',
    'register_dialect',
    'get_dialect',
    'list_dialects',
    'Sniffer',
    'unregister_dialect',
    'DictReader',
    'DictWriter',
    'unix_dialect']
__version__ = '1.0'

class Dialect:
    '''Describe a CSV dialect.

This must be subclassed (see csv.excel).  Valid attributes are:
delimiter, quotechar, escapechar, doublequote, skipinitialspace,
lineterminator, quoting.

'''
    _name = ''
    _valid = False
    delimiter = None
    quotechar = None
    escapechar = None
    doublequote = None
    skipinitialspace = None
    lineterminator = None
    quoting = None
    
    def __init__(self):
        if self.__class__ != Dialect:
            self._valid = True
        self._validate()

    
    def _validate(self):
        
        try:
            _Dialect(self)
        except TypeError as e:
            raise Error(str(e)) from None




class excel(Dialect):
    '''Describe the usual properties of Excel-generated CSV files.'''
    delimiter = ','
    quotechar = '"'
    doublequote = True
    skipinitialspace = False
    lineterminator = '\r\n'
    quoting = QUOTE_MINIMAL

register_dialect('excel', excel)

class excel_tab(excel):
    '''Describe the usual properties of Excel-generated TAB-delimited files.'''
    delimiter = '\t'

register_dialect('excel-tab', excel_tab)

class unix_dialect(Dialect):
    '''Describe the usual properties of Unix-generated CSV files.'''
    delimiter = ','
    quotechar = '"'
    doublequote = True
    skipinitialspace = False
    lineterminator = '\n'
    quoting = QUOTE_ALL

register_dialect('unix', unix_dialect)

class DictReader:
    
    def __init__(self, f, fieldnames = None, restkey = None, restval = None, dialect = 'excel', *args, **kwds):
        if fieldnames is not None and iter(fieldnames) is fieldnames:
            fieldnames = list(fieldnames)
        self._fieldnames = fieldnames
        self.restkey = restkey
        self.restval = restval
        # unsupported CALL_INTRINSIC_1 6
        self.reader = reader(*{
            **kwds })
        self.dialect = dialect
        self.line_num = 0
        return None
    # WARNING: Decompyle incomplete

    
    def __iter__(self):
        return self

    fieldnames = (lambda self: if self._fieldnames is None:
try:
self._fieldnames = next(self.reader)except StopIteration:
passself.line_num = self.reader.line_numself._fieldnames)()
    fieldnames = (lambda self, value: self._fieldnames = value)()
    
    def __next__(self):
        if self.line_num == 0:
            self.fieldnames
        row = next(self.reader)
        self.line_num = self.reader.line_num
        while row == []:
            row = next(self.reader)
        d = dict(zip(self.fieldnames, row))
        lf = len(self.fieldnames)
        lr = len(row)
        if lf < lr:
            d[self.restkey] = row[lf:]
            return d
        if lf > lr:
            for key in self.fieldnames[lr:]:
                d[key] = self.restval
        return d

    __class_getitem__ = classmethod(types.GenericAlias)


class DictWriter:
    
    def __init__(self, f, fieldnames, restval = '', extrasaction = 'raise', dialect = 'excel', *args, **kwds):
        if fieldnames is not None and iter(fieldnames) is fieldnames:
            fieldnames = list(fieldnames)
        self.fieldnames = fieldnames
        self.restval = restval
        extrasaction = extrasaction.lower()
        if extrasaction not in ('raise', 'ignore'):
            raise ValueError("extrasaction (%s) must be 'raise' or 'ignore'" % extrasaction)
        self.extrasaction = extrasaction
        # unsupported CALL_INTRINSIC_1 6
        self.writer = writer(*{
            **kwds })
        return None
    # WARNING: Decompyle incomplete

    
    def writeheader(self):
        header = dict(zip(self.fieldnames, self.fieldnames))
        return self.writerow(header)

    
    def _dict_to_list(self, rowdict):
        '''raise'''
        if self.extrasaction == 'raise':
            wrong_fields = rowdict.keys() - self.fieldnames
            if wrong_fields:
                raise None(ValueError + 'dict contains fields not in fieldnames: '(x))
        return self.fieldnames()

    
    def writerow(self, rowdict):
        return self.writer.writerow(self._dict_to_list(rowdict))

    
    def writerows(self, rowdicts):
        return self.writer.writerows(map(self._dict_to_list, rowdicts))

    __class_getitem__ = classmethod(types.GenericAlias)


class Sniffer:
    '''
"Sniffs" the format of a CSV file (i.e. delimiter, quotechar)
Returns a Dialect object.
'''
    
    def __init__(self):
        ''','''
        self.preferred = [
            ',',
            '\t',
            ';',
            ' ',
            ':']

    
    def sniff(self, sample, delimiters = None):
        '''
Returns a dialect (or None) corresponding to the sample

If several delimiters fit the sample equally well, the
delimiters listed in the preferred attribute are preferred, in
that order, no matter how many times each of them occurs.
'''
        sample = sample.replace('\r\n', '\n').replace('\r', '\n')
        quotechar, doublequote, delimiter, skipinitialspace = self._guess_quote_and_delimiter(sample, delimiters)
        if not delimiter:
            delimiter, skipinitialspace = self._guess_delimiter(sample, delimiters)
        if not delimiter:
            raise Error('Could not determine delimiter')
        
        class dialect(Dialect):
            _name = 'sniffed'
            lineterminator = '\r\n'
            quoting = QUOTE_MINIMAL

        dialect.doublequote = doublequote
        dialect.delimiter = delimiter
        dialect.quotechar = quotechar or '"'
        dialect.skipinitialspace = skipinitialspace
        return dialect

    
    def _guess_quote_and_delimiter(self, data, delimiters):
        """
Looks for text enclosed between two identical quotes
(the probable quotechar) which are preceded and followed
by the same character (the probable delimiter).
For example:
                 ,'some text',
The quote with the most wins, same with the delimiter.
If there is no quotechar the delimiter can't be determined
this way.
"""
        import re
        body = '(?:(?P=quote){2}|(?!(?P=quote)).)*+'
        matches = []
        for restr in ('(?P<delim>[^\\w\\n"\\\'])(?P<space> ?)(?P<quote>["\\\'])%s(?P=quote)(?P=delim)', '(?:^|\\n)(?P<quote>["\\\'])%s(?P=quote)(?P<delim>[^\\w\\n"\\\'])(?P<space> ?)', '(?P<delim>[^\\w\\n"\\\'])(?P<space> ?)(?P<quote>["\\\'])%s(?P=quote)(?:$|\\n)', '(?:^|\\n)(?P<quote>["\\\'])%s(?P=quote)(?:$|\\n)'):
            regexp = re.compile(restr % body, re.DOTALL | re.MULTILINE)
            matches = regexp.findall(data)
            if not matches:
                continue
            ('(?P<delim>[^\\w\\n"\\\'])(?P<space> ?)(?P<quote>["\\\'])%s(?P=quote)(?P=delim)', '(?:^|\\n)(?P<quote>["\\\'])%s(?P=quote)(?P<delim>[^\\w\\n"\\\'])(?P<space> ?)', '(?P<delim>[^\\w\\n"\\\'])(?P<space> ?)(?P<quote>["\\\'])%s(?P=quote)(?:$|\\n)', '(?:^|\\n)(?P<quote>["\\\'])%s(?P=quote)(?:$|\\n)')
        if not matches:
            return ('', False, None, 0)
        quotes = { }
        delims = { }
        spaces = 0
        groupindex = regexp.groupindex
        for m in matches:
            n = groupindex['quote'] - 1
            key = m[n]
            if key:
                quotes[key] = quotes.get(key, 0) + 1
            
            try:
                n = groupindex['delim'] - 1
                key = m[n]
            except KeyError:
                pass

            if key:
                if not (delimiters is not None) or key in delimiters:
                    delims[key] = delims.get(key, 0) + 1
            
            try:
                n = groupindex['space'] - 1
            except KeyError:
                pass

            if not m[n]:
                continue
            spaces += 1
        quotechar = max(quotes, key = quotes.get)
        if delims:
            delim = max(delims, key = delims.get)
            skipinitialspace = delims[delim] == spaces
            if delim == '\n':
                delim = ''
        else:
            delim = ''
            skipinitialspace = 0
        doublequote = False
        if delim:
            dq_regexp = re.compile('(?:(?<=%(delim)s)|^)%(space)s%(quote)s((?:%(quote)s%(quote)s|[^%(quote)s]++)*+)%(quote)s(?:%(delim)s|$)' % {
                'space': ' *+' if delim != ' ' else '',
                'quote': quotechar,
                'delim': re.escape(delim) }, re.MULTILINE)
            dquotechar = quotechar * 2
            if any is any:
                any
                for None in dq_regexp.finditer(data)():
                    while not None:
                        pass
            
            doublequote = (lambda .0: for m in .0:
dquotechar in m[1].0)(dq_regexp.finditer(data)())
        return (quotechar, doublequote, delim, skipinitialspace)

    
    def _guess_delimiter(self, data, delimiters):
        """
The delimiter /should/ occur the same number of times on
each row. However, due to malformed data, it may not. We don't want
an all or nothing approach, so we allow for small variations in this
number.
  1) build a table of the frequency of each character on every line.
  2) build a table of frequencies of this frequency (meta-frequency?),
     e.g.  'x occurred 5 times in 10 rows, 6 times in 1000 rows,
     7 times in 2 rows'
  3) use the mode of the meta-frequency to determine the /expected/
     frequency for that character
  4) find out how often the character actually meets that goal
  5) the character that best meets its goal is the delimiter
For performance reasons, the data is evaluated in chunks, so it can
try and evaluate the smallest portion of the data possible, evaluating
additional chunks as necessary.
"""
        data = list(filter(None, data.split('\n')))
        
        try:
            for c in range(127):
                pass
        c = v
        
        try:
            for k, v in delims.items():
                pass
        v = range(127)
        k = None


        ascii = []
        c = c
        chunkLength = min(10, len(data))
        iteration = 0
        charFrequency = { }
        modes = { }
        delims = { }
        end = 0
        start = chunkLength
        while start < len(data):
            iteration += 1
            for line in data[start:end]:
                for char in ascii:
                    metaFrequency = charFrequency.get(char, { })
                    freq = line.count(char)
                    metaFrequency[freq] = metaFrequency.get(freq, 0) + 1
                    charFrequency[char] = metaFrequency
            for char in charFrequency.keys():
                items = list(charFrequency[char].items())
                if len(items) == 1 and items[0][0] == 0:
                    continue
                if len(items) > 1:
                    modes[char] = max(items, key = (lambda x: x[1]))
                    items.remove(modes[char])
                    modes[char] = (None, sum - (lambda .0: for item in .0:
item[1].0)(items()))
                    continue
                modes[char] = items[0]
            modeList = modes.items()
            total = float(min(chunkLength * iteration, len(data)))
            consistency = 1
            threshold = 0.9
            while len(delims) == 0 and consistency >= threshold:
                for k, v in modeList:
                    while not v[0] > 0:
                        pass
                    if not v[1] > 0:
                        continue
                    if not v[1] / total >= consistency:
                        continue
                    if delimiters is not None and not (k in delimiters):
                        continue
                    delims[k] = v
                consistency -= 0.01
            if len(delims) == 1:
                delim = list(delims.keys())[0]
                skipinitialspace = data[0].count(delim) == data[0].count('%c ' % delim)
                return (delim, skipinitialspace)
            start = end
            end += chunkLength
        if not delims:
            return ('', 0)
        if len(delims) > 1:
            for d in self.preferred:
                while not d in delims.keys():
                    pass
                skipinitialspace = data[0].count(d) == data[0].count('%c ' % d)
                return (d, skipinitialspace)
        
        try:
            for k, v in delims.items():
                pass
        v = range(127)
        k = None

        items = []
        k = k
        v = v
        items.sort()
        delim = items[-1][1]
        skipinitialspace = data[0].count(delim) == data[0].count('%c ' % delim)
        return (delim, skipinitialspace)
    # WARNING: Decompyle incomplete

    
    def has_header(self, sample):
        rdr = reader(StringIO(sample), self.sniff(sample))
        header = next(rdr)
        columns = len(header)
        columnTypes = { }
        for i in range(columns):
            columnTypes[i] = None
        checked = 0
        for row in rdr:
            if checked > 20:
                rdr
            else:
                checked += 1
                if len(row) != columns:
                    continue
                for col in list(columnTypes.keys()):
                    thisType = complex
                    
                    try:
                        thisType(row[col])
                    except (ValueError, OverflowError):
                        thisType = len(row[col])

                    if not thisType != columnTypes[col]:
                        continue
                    if columnTypes[col] is None:
                        columnTypes[col] = thisType
                        continue
                    del columnTypes[col]
        hasHeader = 0
        for col, colType in columnTypes.items():
            while isinstance(colType, int):
                if len(header[col]) != colType:
                    hasHeader += 1
                    continue
                hasHeader -= 1
            
            try:
                colType(header[col])
            except (ValueError, TypeError):
                hasHeader += 1

            hasHeader -= 1
        return hasHeader > 0


